#!/usr/bin/env bun
//
// convert-iata-xlsx.ts
//
// Manual fixture refresh: fetches the upstream IATA-Cargo XFSU Status Codes.xlsx
// and emits the JSON fixture at xfsu-status-codes.json.
//
// Usage:
//   bun run convert-iata-xlsx.ts --only fsu
//
// Run when IATA publishes a working-draft update; commit the fixture diff
// alongside the maintenance PR. The fixture-drift test (this file's sibling)
// fails in CI when the fixture and the FSU_EVENT_CODES const drift apart.

import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import * as XLSX from 'xlsx'

const UPSTREAM_URL =
  'https://github.com/IATA-Cargo/ONE-Record/raw/master/working_draft/Data-Orchestration/CXML-Mapping/XFSU%20Status%20Codes.xlsx'
const FIXTURE_PATH = join(
  process.cwd(),
  'xfsu-status-codes.json',
)

async function fetchAndConvert(): Promise<void> {
  console.log(`Fetching ${UPSTREAM_URL}...`)
  const res = await fetch(UPSTREAM_URL)
  if (!res.ok) {
    throw new Error(`Fetch failed: ${res.status} ${res.statusText}`)
  }
  const buf = await res.arrayBuffer()
  const sha = createHash('sha256').update(new Uint8Array(buf)).digest('hex')
  const wb = XLSX.read(buf, { type: 'array' })
  const sheet = wb.Sheets['Mapping of Status Codes']
  if (!sheet) throw new Error('No sheet found in xlsx')
  const rows = XLSX.utils.sheet_to_json<Record<string, string>>(sheet)
  // Heuristic: extract 3-letter status codes from a column whose name matches /code/i
  const codes: string[] = []
  for (const row of rows) {
    for (const [k, v] of Object.entries(row)) {
      if (/code/i.test(k) && typeof v === 'string' && /^[A-Z]{3}$/.test(v.trim())) {
        codes.push(v.trim())
        break
      }
    }
  }
  if (codes.length === 0) {
    throw new Error('Failed to extract any FSU codes — sheet schema may have changed')
  }
  const sorted = [...new Set(codes)].sort()
  const out = {
    codes: sorted,
    pinnedSha: `sha256:${sha}`,
    source: UPSTREAM_URL,
    note: `Auto-generated by convert-iata-xlsx.ts on ${new Date().toISOString()}`,
  }
  writeFileSync(FIXTURE_PATH, JSON.stringify(out, null, 2) + '\n')
  console.log(`Wrote ${sorted.length} codes to ${FIXTURE_PATH}`)
  console.log(`Upstream SHA: ${sha}`)
}

const args = process.argv.slice(2)
if (args.includes('--only') && args[args.indexOf('--only') + 1] === 'fsu') {
  fetchAndConvert().catch((e) => {
    console.error(e)
    process.exit(1)
  })
} else {
  console.error('Usage: bun run convert-iata-xlsx.ts --only fsu')
  process.exit(1)
}
